#!/usr/bin/env bash
# Bootstrap a repo's 1Password-backed .env: materializes .env from .env.tpl
# (op inject) and writes a skip-if-populated .envrc (direnv), so `op inject`
# -- and any interactive 1Password unlock prompt it can trigger -- only runs
# when .env is missing or stale relative to .env.tpl.
#
# Companion to the vault/rotation architecture in hub-repo's
# T20260510-161133: this script only handles the local .env/.envrc bootstrap
# layer (that task's Layer 2 addendum), not vault design, GHA sync, or
# rotation cadence.

# The .envrc template this skill writes. A function (not a heredoc file) so
# BATS can assert on its exact content without shelling out to a temp file.
pes-envrc-content() {
  cat <<'EOF'
# Auto-generated by /1password-env-setup -- materializes .env from .env.tpl
# via `op inject`, skipping the 1Password round-trip (and any interactive
# unlock prompt) when .env is already populated and not stale relative to
# .env.tpl.
if [ -f .env ] && [ .env -nt .env.tpl ]; then
  : # already materialized and newer than the template -- skip the 1Password round-trip
else
  op inject -i .env.tpl -o .env
fi
dotenv .env
EOF
}

# Verify <dir>/.env.tpl exists; on failure, print guidance to stderr and
# return 1. This skill bootstraps the .env/.envrc *mechanism* -- the
# op:// reference list in .env.tpl is repo-specific and out of scope here.
pes-check-env-tpl() {
  local dir="$1"
  if [ ! -f "$dir/.env.tpl" ]; then
    echo "error: $dir/.env.tpl not found. This skill bootstraps .env/.envrc from an" \
         "existing .env.tpl -- create one first (see hub-repo T20260510-161133 for the" \
         "op:// reference format), then re-run /1password-env-setup." >&2
    return 1
  fi
  return 0
}

# Write <dir>/.envrc with the skip-if-populated template. Idempotent: a
# no-op (prints "unchanged") if the file already has this exact content.
pes-write-envrc() {
  local dir="$1"
  local target="$dir/.envrc"
  local content
  content=$(pes-envrc-content)
  if [ -f "$target" ] && [ "$(cat "$target")" = "$content" ]; then
    echo "unchanged: $target"
    return 0
  fi
  printf '%s\n' "$content" >"$target"
  echo "wrote: $target"
}

# Materialize <dir>/.env from .env.tpl via `op inject`. Same skip-if-populated
# check as the .envrc it writes, so running this script directly (without
# direnv installed) behaves the same as direnv's first `cd`.
pes-materialize-env() {
  local dir="$1"
  if [ -f "$dir/.env" ] && [ "$dir/.env" -nt "$dir/.env.tpl" ]; then
    echo "unchanged: $dir/.env already newer than .env.tpl"
    return 0
  fi
  if ! command -v op >/dev/null 2>&1; then
    echo "op (1Password CLI) not installed -- skipping .env materialization." \
         "Install via 'brew install 1password-cli', then run:" \
         "op inject -i $dir/.env.tpl -o $dir/.env" >&2
    return 0
  fi
  op inject -i "$dir/.env.tpl" -o "$dir/.env"
  echo "materialized: $dir/.env"
}

# Run `direnv allow` in <dir> so the .envrc just written takes effect on the
# next `cd`, without requiring a separate manual approval step.
pes-direnv-allow() {
  local dir="$1"
  if ! command -v direnv >/dev/null 2>&1; then
    echo "direnv not installed -- skipping 'direnv allow'." \
         "Install via 'brew install direnv' (and hook it into your shell), then run:" \
         "direnv allow $dir" >&2
    return 0
  fi
  (cd "$dir" && direnv allow)
}

# Entry point. <dir> defaults to the current directory.
1password-env-setup() {
  local dir
  dir=$(cd "${1:-.}" 2>/dev/null && pwd) || { echo "error: no such directory: ${1:-.}" >&2; return 1; }

  pes-check-env-tpl "$dir" || return 1
  pes-write-envrc "$dir"
  pes-materialize-env "$dir"
  pes-direnv-allow "$dir"
}

# Run only when executed directly (not when sourced), matching the
# statusline-setup/scripts/statusline-command.sh convention so BATS can
# source this file and unit-test the helper functions without invoking the
# real bootstrap.
if [[ "${BASH_SOURCE[0]:-}" == "${0:-}" ]]; then
  1password-env-setup "$@"
fi
